export default {
  GEO_JSON_POPUP: "GEO_JSON_POPUP",
  CAP_POPUP: "CAP_POPUP",
  PHASE_POPUP: "PHASE_POPUP",
  SESSION_POPUP: "SESSION_POPUP",
  ROLE_POPUP: "ROLE_POPUP",
  OST_POPUP: "OST_POPUP",
  LOG_POPUP: "LOG_POPUP",
  EVAL_LOG_POPUP: "EVAL_LOG_POPUP",
  LARGE_DATA_POPUP: "LARGE_DATA_POPUP",
  MAP_LAYER_POPUP: "MP_LAYER_POPUP"
}
